<?php
$viewId=(int)($_GET['view']??0);
if($viewId):$application=fetch_one('SELECT * FROM applications WHERE id=?',[$viewId]);
if(!$application):?><div class="empty-admin">Başvuru bulunamadı.</div><?php else:$data=json_decode($application['data_json'],true)?:[];?>
<div class="application-detail-head"><a href="?section=applications">← Başvuru listesine dön</a><div><span class="badge blue"><?= e(application_label($application['form_type'])) ?></span><span class="badge <?= $application['status']==='Yeni'?'red':'green' ?>"><?= e($application['status']) ?></span></div></div>
<div class="application-detail-grid"><section class="panel"><div class="panel-head"><div><small>BAŞVURU #<?= $application['id'] ?></small><h2>Aday bilgileri</h2></div><time><?= e(date('d.m.Y H:i',strtotime($application['created_at']))) ?></time></div><div class="application-data"><?php foreach($data as $label=>$value):?><div><small><?= e($label) ?></small><p><?= nl2br(e($value)) ?></p></div><?php endforeach; ?></div></section><aside class="panel"><div class="panel-head"><div><small>YÖNETİM İŞLEMİ</small><h2>Değerlendirme</h2></div></div><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf()) ?>"><input type="hidden" name="action" value="application_update"><input type="hidden" name="id" value="<?= $application['id'] ?>"><label>Başvuru durumu<select name="status"><?php foreach(['Yeni','İncelendi','Veli Arandı','Oyuncu Arandı','Denemeye Davet Edildi','Kabul Edildi','Uygun Değil','Arşivlendi'] as $status):?><option <?= $application['status']===$status?'selected':'' ?>><?= e($status) ?></option><?php endforeach; ?></select></label><label>Yönetici notu<textarea name="admin_note" placeholder="Görüşme, deneme tarihi ve değerlendirme notları..."><?= e($application['admin_note']) ?></textarea></label><button class="primary-button">Değerlendirmeyi Kaydet</button></form><hr><form method="post" onsubmit="return confirm('Başvuru kalıcı olarak silinsin mi?')"><input type="hidden" name="csrf" value="<?= e(csrf()) ?>"><input type="hidden" name="action" value="delete_generic"><input type="hidden" name="table" value="applications"><input type="hidden" name="id" value="<?= $application['id'] ?>"><button class="danger-button">Başvuruyu Sil</button></form></aside></div>
<?php endif;else:
$type=$_GET['type']??'';$status=$_GET['status']??'';$search=trim((string)($_GET['q']??''));
$where=[];$params=[];if(in_array($type,['academy','first_team'],true)){$where[]='form_type=?';$params[]=$type;}if($status!==''){$where[]='status=?';$params[]=$status;}if($search!==''){$where[]='data_json LIKE ?';$params[]='%'.$search.'%';}$sql='SELECT * FROM applications'.($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY created_at DESC';$rows=fetch_all($sql,$params);
?>
<section class="panel"><div class="panel-head"><div><small>OYUNCU ADAY HAVUZU</small><h2>Başvurular</h2></div><div class="export-note">Her başvuru ayrı detay sayfasında değerlendirilir.</div></div><form method="get" class="filter-bar"><input type="hidden" name="section" value="applications"><input name="q" value="<?= e($search) ?>" placeholder="İsim, telefon, mevki veya kulüp ara..."><select name="type"><option value="">Tüm başvurular</option><option value="academy" <?= $type==='academy'?'selected':'' ?>>Altyapı</option><option value="first_team" <?= $type==='first_team'?'selected':'' ?>>A Takım</option></select><select name="status"><option value="">Tüm durumlar</option><?php foreach(['Yeni','İncelendi','Veli Arandı','Oyuncu Arandı','Denemeye Davet Edildi','Kabul Edildi','Uygun Değil','Arşivlendi'] as $value):?><option <?= $status===$value?'selected':'' ?>><?= e($value) ?></option><?php endforeach; ?></select><button>Filtrele</button><a href="?section=applications">Temizle</a></form><div class="application-inbox"><?php foreach($rows as $row):$data=json_decode($row['data_json'],true)?:[];$name=$data['Ad Soyad']??$data['Ad Soyad *']??'İsimsiz Başvuru';$phone=$data['Telefon']??$data['Telefon *']??'';$positions=$data['Oynadığı Mevkiler']??'';$previous=$data['Önceki Kulüp veya Futbol Okulları']??'';?><a href="?section=applications&view=<?= $row['id'] ?>"><div class="app-avatar"><?= e(mb_substr($name,0,1)) ?></div><div class="app-primary"><small><?= e(application_label($row['form_type'])) ?></small><h3><?= e($name) ?></h3><p><?= e($phone) ?><?= $positions?' · '.$positions:'' ?></p><?php if($previous):?><span>Önceki: <?= e($previous) ?></span><?php endif; ?></div><div class="app-date"><span class="badge <?= $row['status']==='Yeni'?'red':'blue' ?>"><?= e($row['status']) ?></span><time><?= e(date('d.m.Y H:i',strtotime($row['created_at']))) ?></time></div><em>Detayı aç →</em></a><?php endforeach; ?><?php if(!$rows):?><div class="empty-admin">Filtreye uygun başvuru bulunamadı.</div><?php endif; ?></div></section>
<?php endif; ?>
