<?php
$type=($_GET['type']??'academy')==='first_team'?'first_team':'academy';
$edit=isset($_GET['edit'])?fetch_one('SELECT * FROM form_fields WHERE id=?',[(int)$_GET['edit']]):null;
if($edit){$type=$edit['form_type'];}
$rows=fetch_all('SELECT * FROM form_fields WHERE form_type=? ORDER BY sort_order,id',[$type]);
$fieldTypes=['text'=>'Kısa metin','textarea'=>'Uzun açıklama','tel'=>'Telefon','email'=>'E-posta','date'=>'Tarih','number'=>'Sayı','select'=>'Tek seçim listesi','multiselect'=>'Çoklu seçim','checkbox'=>'Onay kutusu'];
?>
<div class="form-type-switch"><a class="<?= $type==='academy'?'active':'' ?>" href="?section=forms&type=academy"><small>01</small><b>Altyapı Başvuru Formu</b><span>Çocuklar ve yaş grupları</span></a><a class="<?= $type==='first_team'?'active':'' ?>" href="?section=forms&type=first_team"><small>02</small><b>A Takım Başvuru Formu</b><span>Yetişkin ve deneme talepleri</span></a></div>
<div class="split-layout">
<form method="post" class="panel form-panel live-form"><input type="hidden" name="csrf" value="<?= e(csrf()) ?>"><input type="hidden" name="action" value="form_field_save"><input type="hidden" name="id" value="<?= e($edit['id']??'') ?>"><input type="hidden" name="form_type" value="<?= e($type) ?>"><div class="panel-head"><div><small>DİNAMİK FORM ALANLARI</small><h2><?= $edit?'Alanı düzenle':'Yeni form alanı ekle' ?></h2></div><?php if($edit):?><a href="?section=forms&type=<?= e($type) ?>">Yeni alan +</a><?php endif; ?></div><div class="form-grid"><label>Alan başlığı<input name="label" value="<?= e($edit['label']??'') ?>" data-live="field-label" placeholder="Oynadığı Mevkiler" required></label><label>Teknik alan adı<input name="name" value="<?= e($edit['name']??'') ?>" placeholder="positions"><small>Boş bırakırsanız başlıktan oluşturulur.</small></label><label>Alan türü<select name="field_type" data-live="field-type"><?php foreach($fieldTypes as $value=>$label):?><option value="<?= e($value) ?>" <?= ($edit['field_type']??'text')===$value?'selected':'' ?>><?= e($label) ?></option><?php endforeach; ?></select></label><label>Sıralama<input type="number" name="sort_order" value="<?= e($edit['sort_order']??0) ?>"></label><label class="full">Seçenekler<textarea name="options" data-live="field-options" placeholder="Her seçeneği yeni satıra yazın&#10;Kaleci&#10;Stoper&#10;Sağ Bek"><?= e($edit['options']??'') ?></textarea><small>Select ve çoklu seçim alanlarında kullanılır.</small></label><label class="full">Örnek / placeholder<input name="placeholder" value="<?= e($edit['placeholder']??'') ?>" data-live="field-placeholder"></label><label class="full">Yardım metni<input name="help_text" value="<?= e($edit['help_text']??'') ?>" data-live="field-help"></label><label class="check"><input type="checkbox" name="required" <?= ($edit['required']??0)?'checked':'' ?>><span>Zorunlu alan</span></label><label class="check"><input type="checkbox" name="active" <?= ($edit['active']??1)?'checked':'' ?>><span>Formda göster</span></label></div><button class="primary-button">Form Alanını Kaydet</button></form>
<aside class="preview-column sticky-preview"><div class="preview-label">CANLI FORM ÖNİZLEMESİ</div><div class="form-admin-preview"><small><?= e(application_label($type)) ?></small><h3>Başvuru Bilgileri</h3><label><span data-preview="field-label"><?= e($edit['label']??'Alan Başlığı') ?></span><em data-required-preview><?= ($edit['required']??0)?'*':'' ?></em><div class="dynamic-field-preview" data-field-preview data-type="<?= e($edit['field_type']??'text') ?>"><input disabled placeholder="<?= e($edit['placeholder']??'Örnek metin') ?>"></div><p data-preview="field-help"><?= e($edit['help_text']??'Alan yardım metni') ?></p></label><button>Başvuruyu Gönder</button></div></aside></div>
<section class="panel"><div class="panel-head"><div><small><?= e(mb_strtoupper(application_label($type))) ?></small><h2>Form alanları ve zorunluluklar</h2></div><a href="<?= e(url('index.php?page=application&type='.$type)) ?>" target="_blank">Formu sitede aç ↗</a></div><div class="field-list"><?php foreach($rows as $row):?><article><span class="drag-handle">⋮⋮</span><div><small><?= e($fieldTypes[$row['field_type']]??$row['field_type']) ?> · Sıra <?= e($row['sort_order']) ?></small><h3><?= e($row['label']) ?><?= $row['required']?' *':'' ?></h3><p><?= e($row['placeholder']?:$row['help_text']) ?></p></div><span class="badge <?= $row['active']?'green':'gray' ?>"><?= $row['active']?'Aktif':'Gizli' ?></span><div class="row-actions"><a href="?section=forms&type=<?= e($type) ?>&edit=<?= $row['id'] ?>">Düzenle</a><form method="post" onsubmit="return confirm('Form alanı silinsin mi?')"><input type="hidden" name="csrf" value="<?= e(csrf()) ?>"><input type="hidden" name="action" value="delete_generic"><input type="hidden" name="table" value="form_fields"><input type="hidden" name="id" value="<?= $row['id'] ?>"><button class="danger-link">Sil</button></form></div></article><?php endforeach; ?></div></section>
