<?php
$teams = fetch_all('SELECT * FROM teams ORDER BY sort_order,id');
$edit = isset($_GET['edit']) ? fetch_one('SELECT * FROM players WHERE id=?', [(int) $_GET['edit']]) : null;
$selected = selected_positions($edit['positions']??[]);
$filterTeam = (int)($_GET['team']??0);
$params=[];$where='1=1';if($filterTeam){$where.=' AND p.team_id=?';$params[]=$filterTeam;}
$players = fetch_all("SELECT p.*,t.name team_name,t.logo team_logo,t.accent team_accent FROM players p JOIN teams t ON t.id=p.team_id WHERE {$where} ORDER BY p.active DESC,t.sort_order,p.sort_order,p.jersey_no",$params);
$usedNumbers=[];foreach($teams as $team){$usedNumbers[$team['id']]=array_map('intval',array_column(fetch_all('SELECT jersey_no FROM players WHERE team_id=? AND active=1 AND jersey_no IS NOT NULL',[$team['id']]),'jersey_no'));}
?>
<div class="split-layout wide-preview">
<form method="post" enctype="multipart/form-data" class="panel form-panel live-form" data-used-numbers='<?= e(json_encode($usedNumbers)) ?>' data-edit-id="<?= e($edit['id']??0) ?>" data-edit-number="<?= e($edit['jersey_no']??0) ?>">
<input type="hidden" name="csrf" value="<?= e(csrf()) ?>"><input type="hidden" name="action" value="player_save"><input type="hidden" name="id" value="<?= e($edit['id']??'') ?>"><input type="hidden" name="old_photo" value="<?= e($edit['photo']??'') ?>">
<div class="panel-head"><div><small>KADRO YÖNETİMİ</small><h2><?= $edit?'Oyuncuyu düzenle':'Yeni oyuncu ekle' ?></h2></div><?php if($edit):?><a href="?section=players">Yeni oyuncu +</a><?php endif; ?></div>
<div class="form-grid"><label>Takım<select name="team_id" data-player-team required><?php foreach($teams as $team):?><option value="<?= $team['id'] ?>" data-name="<?= e($team['name']) ?>" data-logo="<?= e($team['logo']?media_url($team['logo']):'') ?>" data-accent="<?= e($team['accent']) ?>" <?= ($edit['team_id']??0)==$team['id']?'selected':'' ?>><?= e($team['name']) ?></option><?php endforeach; ?></select></label><label>Ad soyad<input name="name" value="<?= e($edit['name']??'') ?>" data-live="player-name" required></label><label>URL kısa adı<input name="slug" value="<?= e($edit['slug']??'') ?>" placeholder="oyuncu-adi"></label><label>Forma numarası (1-99)<input type="number" min="1" max="99" name="jersey_no" value="<?= e($edit['jersey_no']??'') ?>" data-live="player-number" required><small class="field-status" data-number-status>Seçilen takımda benzersiz olmalıdır.</small></label>
<fieldset class="full position-picker"><legend>Oynadığı mevkiler</legend><?php foreach(positions() as $position):?><label><input type="checkbox" name="positions[]" value="<?= e($position) ?>" <?= in_array($position,$selected,true)?'checked':'' ?> data-position><span><?= e($position) ?></span></label><?php endforeach; ?></fieldset>
<label>Doğum tarihi<input type="date" name="birth_date" value="<?= e($edit['birth_date']??'') ?>"></label><label>Boy (cm)<input type="number" min="120" max="230" name="height" value="<?= e($edit['height']??'') ?>" data-live="player-height"></label><label>Tercih ettiği ayak<select name="preferred_foot" data-live="player-foot"><option value="">Seçiniz</option><?php foreach(['Sağ','Sol','Her İkisi'] as $foot):?><option <?= ($edit['preferred_foot']??'')===$foot?'selected':'' ?>><?= e($foot) ?></option><?php endforeach; ?></select></label><label>Uyruk<input name="nationality" value="<?= e($edit['nationality']??'Türkiye') ?>"></label><label class="full">Önceki kulüpler ve sezonlar<textarea name="previous_clubs" data-live="player-clubs" placeholder="Sivas ... Spor (2023-2025)&#10;Futbol Okulu ..."><?= e($edit['previous_clubs']??'') ?></textarea><small>Birden fazla kulübü alt alta yazabilirsiniz.</small></label><label>Oyuncu fotoğrafı<input type="file" name="photo_file" accept="image/jpeg,image/png,image/webp" data-image-preview="player-photo"></label><label>Fotoğraf URL<input name="photo_url" data-url-preview="player-photo" placeholder="https://..."></label><label class="full">Oyuncu tanıtımı<textarea name="bio" data-live="player-bio"><?= e($edit['bio']??'') ?></textarea></label><label>Sıralama<input type="number" name="sort_order" value="<?= e($edit['sort_order']??0) ?>"></label><label class="check"><input type="checkbox" name="featured" <?= ($edit['featured']??0)?'checked':'' ?>><span>Ana sayfa vitrininde göster</span></label><label class="check"><input type="checkbox" name="active" <?= ($edit['active']??1)?'checked':'' ?>><span>Aktif kadroda göster</span></label></div>
<div class="upload-note"><b>Oyuncu fotoğraf önerisi</b><span>PNG/WEBP, şeffaf veya temiz arka plan, dikey 1000×1400 px. Fotoğraf eklenmezse sistem otomatik silüet kullanır.</span></div><button class="primary-button">Oyuncuyu Kaydet</button>
</form>
<aside class="preview-column sticky-preview"><div class="preview-label">CANLI OYUNCU KARTI</div><div class="player-admin-card" style="--player-accent:<?= e($edit?($teams[array_search($edit['team_id'],array_column($teams,'id'))]['accent']??'#e3062f'):'#e3062f') ?>;--player-watermark:url('<?= e($edit && !empty($edit['team_logo'])?media_url($edit['team_logo']):'') ?>')"><strong data-preview="player-number"><?= e($edit['jersey_no']??'10') ?></strong><img id="player-photo" src="<?= e(!empty($edit['photo'])?media_url($edit['photo']):silhouette()) ?>" alt=""><div><small data-player-position-preview><?= e(mb_strtoupper($selected[0]??'MEVKİ')) ?></small><h3 data-preview="player-name"><?= e($edit['name']??'OYUNCU ADI') ?></h3></div><footer><b>#<span data-preview="player-number"><?= e($edit['jersey_no']??'10') ?></span> · <span data-player-position-preview><?= e($selected[0]??'Mevki') ?></span></b><span><i data-preview="player-height"><?= e($edit['height']??'-') ?></i> cm · <i data-preview="player-foot"><?= e($edit['preferred_foot']??'-') ?></i> ayak</span></footer></div><div class="mini-pitch-preview"><div class="pitch-lines"></div><?php $coords=['Kaleci'=>[50,91],'Stoper'=>[50,73],'Sağ Bek'=>[82,72],'Sol Bek'=>[18,72],'Ön Libero'=>[50,58],'Merkez Orta Saha'=>[50,48],'On Numara'=>[50,35],'Sağ Kanat'=>[82,31],'Sol Kanat'=>[18,31],'Forvet'=>[50,15]];foreach($coords as $position=>[$x,$y]):?><span data-pitch-position="<?= e($position) ?>" class="<?= in_array($position,$selected,true)?'active':'' ?>" style="left:<?= $x ?>%;top:<?= $y ?>%"><?= e($position) ?></span><?php endforeach; ?></div></aside>
</div>
<section class="panel"><div class="panel-head"><div><small>KADRO LİSTESİ</small><h2>Oyuncular</h2></div><form method="get" class="inline-filter"><input type="hidden" name="section" value="players"><select name="team" onchange="this.form.submit()"><option value="0">Tüm takımlar</option><?php foreach($teams as $team):?><option value="<?= $team['id'] ?>" <?= $filterTeam===$team['id']?'selected':'' ?>><?= e($team['name']) ?></option><?php endforeach; ?></select></form></div><div class="admin-player-grid"><?php foreach($players as $player):$pos=selected_positions($player['positions']);?><article class="admin-player-row <?= $player['active']?'':'archived' ?>"><img src="<?= e($player['photo']?media_url($player['photo']):silhouette()) ?>" alt=""><div><small><?= e($player['team_name']) ?> · <?= e(implode(', ',$pos)) ?></small><h3>#<?= e($player['jersey_no']??'-') ?> <?= e($player['name']) ?></h3><p><?= e($player['previous_clubs']?:'Önceki kulüp bilgisi yok') ?></p></div><span class="badge <?= $player['active']?'green':'gray' ?>"><?= $player['active']?'Aktif':'Arşiv' ?></span><div class="row-actions"><a href="?section=players&edit=<?= $player['id'] ?>">Düzenle</a><a href="<?= e(url('index.php?page=player&slug='.urlencode($player['slug']))) ?>" target="_blank">Profil ↗</a><?php if($player['active']):?><form method="post" onsubmit="return confirm('Oyuncu arşivlensin ve forma numarası serbest bırakılsın mı?')"><input type="hidden" name="csrf" value="<?= e(csrf()) ?>"><input type="hidden" name="action" value="player_archive"><input type="hidden" name="id" value="<?= $player['id'] ?>"><button class="danger-link">Arşivle</button></form><?php endif; ?></div></article><?php endforeach; ?><?php if(!$players):?><div class="empty-admin">Henüz oyuncu eklenmedi.</div><?php endif; ?></div></section>
