<?php $logo=setting('site_logo');$hero=setting('hero_image'); ?>
<div class="split-layout">
<form method="post" enctype="multipart/form-data" class="panel form-panel live-form" data-preview-type="site">
<input type="hidden" name="csrf" value="<?= e(csrf()) ?>"><input type="hidden" name="action" value="settings_save">
<div class="panel-head"><div><small>KURUMSAL KİMLİK</small><h2>Site ayarları</h2></div><span class="save-state">Canlı önizleme açık</span></div>
<div class="admin-tabs"><button type="button" class="tab active" data-tab="identity">Kimlik</button><button type="button" class="tab" data-tab="hero">Ana Sayfa</button><button type="button" class="tab" data-tab="corporate">Kurumsal</button><button type="button" class="tab" data-tab="contact">İletişim</button></div>
<div class="tab-panel active" data-panel="identity"><div class="form-grid"><label>Kulüp adı<input name="site_name" value="<?= e(setting('site_name')) ?>" data-live="site-name" required></label><label>Kısa ad<input name="site_short_name" value="<?= e(setting('site_short_name')) ?>" data-live="site-short"></label><label>Üst slogan<input name="site_tagline" value="<?= e(setting('site_tagline')) ?>" data-live="site-tagline"></label><label>Lig adı<input name="league_name" value="<?= e(setting('league_name')) ?>" data-live="site-league"></label><label>Ana renk<input type="color" name="primary_color" value="<?= e(setting('primary_color','#e3062f')) ?>" data-live-color="primary"></label><label>Koyu renk<input type="color" name="dark_color" value="<?= e(setting('dark_color','#0b0e14')) ?>" data-live-color="dark"></label><label>Arka plan rengi<input type="color" name="surface_color" value="<?= e(setting('surface_color','#f4f5f7')) ?>" data-live-color="surface"></label><label>Logo dosyası<input type="file" name="site_logo_file" accept="image/jpeg,image/png,image/webp,image/gif" data-image-preview="site-logo"></label><label>Logo URL<input name="site_logo_url" placeholder="https://..." data-url-preview="site-logo"></label></div><div class="upload-note"><b>Logo önerisi</b><span>PNG veya WEBP, şeffaf arka plan, en az 600×600 px, en fazla 5 MB.</span></div></div>
<div class="tab-panel" data-panel="hero"><div class="form-grid"><label>Üst başlık<input name="hero_eyebrow" value="<?= e(setting('hero_eyebrow')) ?>" data-live="hero-eyebrow"></label><label>Ana başlık<input name="hero_title" value="<?= e(setting('hero_title')) ?>" data-live="hero-title"></label><label class="full">Ana açıklama<textarea name="hero_text" data-live="hero-text"><?= e(setting('hero_text')) ?></textarea></label><label>Kapak görseli<input type="file" name="hero_image_file" accept="image/jpeg,image/png,image/webp" data-image-preview="hero-image"></label><label>Kapak görsel URL<input name="hero_image_url" placeholder="https://..." data-url-preview="hero-image"></label></div><div class="upload-note"><b>Ana kapak önerisi</b><span>JPG veya WEBP, 1920×1080 px ya da 2000×1200 px, yatay ve yüksek kaliteli.</span></div></div>
<div class="tab-panel" data-panel="corporate"><div class="form-grid"><label>Kurumsal bölüm başlığı<input name="about_title" value="<?= e(setting('about_title')) ?>" data-live="about-title"></label><label class="full">Kurumsal açıklama<textarea name="about_text" data-live="about-text"><?= e(setting('about_text')) ?></textarea></label><label class="full">Vizyon<textarea name="vision_text"><?= e(setting('vision_text')) ?></textarea></label><label class="full">Misyon<textarea name="mission_text"><?= e(setting('mission_text')) ?></textarea></label><label class="full">Alt bilgi açıklaması<textarea name="footer_text" data-live="footer-text"><?= e(setting('footer_text')) ?></textarea></label></div></div>
<div class="tab-panel" data-panel="contact"><div class="form-grid"><label>Şehir<input name="contact_city" value="<?= e(setting('contact_city')) ?>"></label><label>Genel e-posta<input type="email" name="contact_email" value="<?= e(setting('contact_email')) ?>"></label><label>Telefon<input name="contact_phone" value="<?= e(setting('contact_phone')) ?>"></label></div><p class="hint">Instagram, Facebook, WhatsApp, adres ve diğer iletişim kayıtlarını “İletişim & Sosyal” bölümünden ayrı ayrı yönetin.</p></div>
<button class="primary-button">Tüm Ayarları Kaydet</button>
</form>
<aside class="preview-column sticky-preview"><div class="preview-label">CANLI SİTE ÖNİZLEMESİ</div><div class="site-live-preview" style="--preview-primary:<?= e(setting('primary_color','#e3062f')) ?>;--preview-dark:<?= e(setting('dark_color','#0b0e14')) ?>;--preview-surface:<?= e(setting('surface_color','#f4f5f7')) ?>"><header><div class="mini-brand"><?php if($logo):?><img id="site-logo" src="<?= e(media_url($logo)) ?>" alt=""><?php else:?><b id="site-logo-fallback"><?= e(setting('site_short_name','SGB')) ?></b><?php endif; ?><span><strong data-preview="site-name"><?= e(setting('site_name')) ?></strong><small data-preview="site-league"><?= e(setting('league_name')) ?></small></span></div><nav>ANA SAYFA · TAKIMLAR · HABERLER</nav></header><section id="hero-image" class="mini-hero" style="background-image:linear-gradient(90deg,rgba(5,7,12,.92),rgba(5,7,12,.55)),url('<?= e($hero?media_url($hero):'') ?>')"><small data-preview="hero-eyebrow"><?= e(setting('hero_eyebrow')) ?></small><h3 data-preview="hero-title"><?= e(setting('hero_title')) ?></h3><p data-preview="hero-text"><?= e(setting('hero_text')) ?></p><button>Kulübe Katıl</button></section><section class="mini-about"><small>KULÜP KÜLTÜRÜ</small><h4 data-preview="about-title"><?= e(setting('about_title')) ?></h4><p data-preview="about-text"><?= e(setting('about_text')) ?></p></section><footer data-preview="footer-text"><?= e(setting('footer_text')) ?></footer></div></aside>
</div>
