<?php
$edit=isset($_GET['edit'])?fetch_one('SELECT * FROM socials WHERE id=?',[(int)$_GET['edit']]):null;
$rows=fetch_all('SELECT * FROM socials ORDER BY sort_order,id');
$types=['instagram'=>'Instagram','facebook'=>'Facebook','x'=>'X / Twitter','youtube'=>'YouTube','tiktok'=>'TikTok','whatsapp'=>'WhatsApp','email'=>'E-posta','phone'=>'Telefon','address'=>'Açık Adres','link'=>'Diğer Bağlantı'];
?>
<div class="split-layout">
<form method="post" class="panel form-panel live-form"><input type="hidden" name="csrf" value="<?= e(csrf()) ?>"><input type="hidden" name="action" value="social_save"><input type="hidden" name="id" value="<?= e($edit['id']??'') ?>"><div class="panel-head"><div><small>İLETİŞİM MERKEZİ</small><h2><?= $edit?'Kaydı düzenle':'İletişim veya sosyal medya ekle' ?></h2></div><?php if($edit):?><a href="?section=socials">Yeni kayıt +</a><?php endif; ?></div><div class="form-grid"><label>Görünen ad<input name="label" value="<?= e($edit['label']??'') ?>" data-live="social-label" placeholder="Instagram, Kulüp Telefonu..." required></label><label>Tür<select name="type" data-live="social-type"><?php foreach($types as $value=>$label):?><option value="<?= e($value) ?>" <?= ($edit['type']??'instagram')===$value?'selected':'' ?>><?= e($label) ?></option><?php endforeach; ?></select></label><label class="full">Değer<input name="value" value="<?= e($edit['value']??'') ?>" data-live="social-value" placeholder="URL, e-posta, telefon veya açık adres" required><small data-social-help>Instagram ve bağlantılarda https:// ile başlayan tam adres kullanın.</small></label><label>Özel ikon sınıfı<input name="icon" value="<?= e($edit['icon']??'') ?>" placeholder="İsteğe bağlı"></label><label>Sıralama<input type="number" name="sort_order" value="<?= e($edit['sort_order']??0) ?>"></label><label class="check"><input type="checkbox" name="active" <?= ($edit['active']??1)?'checked':'' ?>><span>Sitede göster</span></label></div><div class="upload-note"><b>Türlere göre davranış</b><span>E-posta mail uygulamasını, telefon aramayı, WhatsApp sohbeti açar. Açık adres düz metin görünür; kendiliğinden bağlantıya çevrilmez.</span></div><button class="primary-button">İletişim Kaydını Kaydet</button></form>
<aside class="preview-column sticky-preview"><div class="preview-label">CANLI ÜST MENÜ / FOOTER ÖNİZLEMESİ</div><div class="social-admin-preview"><header><span>Önceliğimiz Gençlerimiz</span><a><b data-preview="social-label"><?= e($edit['label']??'Instagram') ?></b> ↗</a></header><footer><small>İLETİŞİM</small><h3 data-preview="social-label"><?= e($edit['label']??'İletişim Başlığı') ?></h3><p data-preview="social-value"><?= e($edit['value']??'İletişim bilgisi') ?></p><span data-preview="social-type"><?= e($types[$edit['type']??'instagram']??'Bağlantı') ?></span></footer></div></aside></div>
<section class="panel"><div class="panel-head"><div><small>YAYINLANAN İLETİŞİM BİLGİLERİ</small><h2>Sosyal medya ve iletişim</h2></div><span><?= count($rows) ?> kayıt</span></div><div class="social-admin-list"><?php foreach($rows as $row):$href=social_href($row);?><article><i><?= match($row['type']){'instagram'=>'◎','facebook'=>'f','youtube'=>'▶','tiktok'=>'♪','whatsapp'=>'◉','email'=>'@','phone'=>'☎','address'=>'⌖',default=>'↗'} ?></i><div><small><?= e($types[$row['type']]??$row['type']) ?></small><h3><?= e($row['label']) ?></h3><p><?= e($row['value']) ?></p></div><span class="badge <?= $row['active']?'green':'gray' ?>"><?= $row['active']?'Aktif':'Gizli' ?></span><div class="row-actions"><?php if($href):?><a href="<?= e($href) ?>" target="_blank">Test Et ↗</a><?php endif; ?><a href="?section=socials&edit=<?= $row['id'] ?>">Düzenle</a><form method="post" onsubmit="return confirm('İletişim kaydı silinsin mi?')"><input type="hidden" name="csrf" value="<?= e(csrf()) ?>"><input type="hidden" name="action" value="delete_generic"><input type="hidden" name="table" value="socials"><input type="hidden" name="id" value="<?= $row['id'] ?>"><button class="danger-link">Sil</button></form></div></article><?php endforeach; ?><?php if(!$rows):?><div class="empty-admin">Henüz iletişim kaydı eklenmedi.</div><?php endif; ?></div></section>
