<?php
$edit=isset($_GET['edit'])?fetch_one('SELECT * FROM sponsors WHERE id=?',[(int)$_GET['edit']]):null;
$rows=fetch_all('SELECT * FROM sponsors ORDER BY sort_order,id');
$guides=[
 ['logo','Sponsor Logo Şeridi','600×240 px','PNG veya WEBP','Şeffaf arka plan, en fazla 3 MB'],
 ['home_banner','Ana Sayfa Yatay Banner','1600×400 px','JPG, PNG veya WEBP','Yazılar merkezde, en fazla 5 MB'],
 ['sidebar','İç Sayfa Dikey Reklam','600×900 px','JPG veya WEBP','Dikey 2:3 oran, en fazla 5 MB'],
 ['footer','Footer Sponsor Alanı','800×300 px','PNG veya WEBP','Şeffaf ya da koyu zemin uyumlu'],
];
?>
<div class="sponsor-guides"><div class="panel-head"><div><small>GÖRSEL TEKNİK ŞARTLARI</small><h2>Sponsor ve reklam ölçüleri</h2></div><span>İçerik yoksa alan sitede hiç görünmez</span></div><div class="guide-grid"><?php foreach($guides as [$key,$title,$size,$types,$note]):?><article><i><?= $key==='logo'?'▰':($key==='home_banner'?'▱':($key==='sidebar'?'▯':'▬')) ?></i><small><?= e($key) ?></small><h3><?= e($title) ?></h3><b><?= e($size) ?></b><p><?= e($types) ?></p><span><?= e($note) ?></span></article><?php endforeach; ?></div></div>
<div class="split-layout">
<form method="post" enctype="multipart/form-data" class="panel form-panel live-form"><input type="hidden" name="csrf" value="<?= e(csrf()) ?>"><input type="hidden" name="action" value="sponsor_save"><input type="hidden" name="id" value="<?= e($edit['id']??'') ?>"><input type="hidden" name="old_image" value="<?= e($edit['image']??'') ?>"><div class="panel-head"><div><small>TİCARİ ALAN YÖNETİMİ</small><h2><?= $edit?'Sponsor alanını düzenle':'Sponsor veya reklam ekle' ?></h2></div><?php if($edit):?><a href="?section=sponsors">Yeni kayıt +</a><?php endif; ?></div><div class="form-grid"><label>Sponsor / marka adı<input name="name" value="<?= e($edit['name']??'') ?>" data-live="sponsor-name" required></label><label>Hedef bağlantı<input type="url" name="website" value="<?= e($edit['website']??'') ?>" placeholder="https://..."></label><label>Yerleşim<select name="placement" data-live="sponsor-placement"><?php foreach($guides as [$key,$title]):?><option value="<?= e($key) ?>" <?= ($edit['placement']??'logo')===$key?'selected':'' ?>><?= e($title) ?></option><?php endforeach; ?></select></label><label>Sıralama<input type="number" name="sort_order" value="<?= e($edit['sort_order']??0) ?>"></label><label>Görsel dosyası<input type="file" name="image_file" accept="image/jpeg,image/png,image/webp,image/gif" data-image-preview="sponsor-image" data-dimension-output="sponsor-dimensions"></label><label>Görsel URL<input name="image_url" data-url-preview="sponsor-image" placeholder="https://..."></label><label>Kaynak genişlik (isteğe bağlı)<input type="number" name="width" value="<?= e($edit['width']??'') ?>" placeholder="1600"></label><label>Kaynak yükseklik (isteğe bağlı)<input type="number" name="height" value="<?= e($edit['height']??'') ?>" placeholder="400"></label><label>Yayın başlangıcı<input type="date" name="starts_at" value="<?= e($edit['starts_at']??'') ?>"></label><label>Yayın bitişi<input type="date" name="ends_at" value="<?= e($edit['ends_at']??'') ?>"></label><label class="check"><input type="checkbox" name="active" <?= ($edit['active']??1)?'checked':'' ?>><span>Yayında</span></label></div><div class="upload-note"><b>Seçilen görsel</b><span id="sponsor-dimensions">Dosya seçildiğinde gerçek piksel ölçüsü ve dosya boyutu burada gösterilir.</span></div><button class="primary-button">Sponsor Alanını Kaydet</button></form>
<aside class="preview-column sticky-preview"><div class="preview-label">CANLI SPONSOR ÖNİZLEMESİ</div><div class="sponsor-admin-preview"><small data-preview="sponsor-placement"><?= e($edit['placement']??'logo') ?></small><div><img id="sponsor-image" src="<?= e(!empty($edit['image'])?media_url($edit['image']):placeholder_logo()) ?>" alt=""></div><h3 data-preview="sponsor-name"><?= e($edit['name']??'Sponsor Adı') ?></h3><p>Alan yalnız aktif bir görsel olduğunda ziyaretçiye gösterilir.</p></div></aside></div>
<section class="panel"><div class="panel-head"><div><small>YAYINDAKİ DESTEKÇİLER</small><h2>Sponsor ve reklam kayıtları</h2></div><span><?= count($rows) ?> kayıt</span></div><div class="sponsor-admin-list"><?php foreach($rows as $row):?><article><img src="<?= e(media_url($row['image'])) ?>" alt=""><div><small><?= e($row['placement']) ?></small><h3><?= e($row['name']) ?></h3><p><?= e($row['width']?:'-') ?>×<?= e($row['height']?:'-') ?> px · <?= e($row['starts_at']?:'Süresiz') ?> / <?= e($row['ends_at']?:'Süresiz') ?></p></div><span class="badge <?= $row['active']?'green':'gray' ?>"><?= $row['active']?'Yayında':'Kapalı' ?></span><div class="row-actions"><a href="?section=sponsors&edit=<?= $row['id'] ?>">Düzenle</a><form method="post" onsubmit="return confirm('Sponsor kaydı silinsin mi?')"><input type="hidden" name="csrf" value="<?= e(csrf()) ?>"><input type="hidden" name="action" value="delete_generic"><input type="hidden" name="table" value="sponsors"><input type="hidden" name="id" value="<?= $row['id'] ?>"><button class="danger-link">Sil</button></form></div></article><?php endforeach; ?><?php if(!$rows):?><div class="empty-admin">Sponsor eklenmedi; sitede boş reklam alanı görünmeyecek.</div><?php endif; ?></div></section>
