<?php
$teams=fetch_all('SELECT * FROM teams ORDER BY sort_order,id');
$edit=isset($_GET['edit'])?fetch_one('SELECT * FROM staff WHERE id=?',[(int)$_GET['edit']]):null;
$rows=fetch_all('SELECT s.*,t.name team_name FROM staff s LEFT JOIN teams t ON t.id=s.team_id ORDER BY s.active DESC,s.sort_order,s.id');
$roles=['Kulüp Başkanı','Başkan Yardımcısı','Yönetim Kurulu Üyesi','Sportif Direktör','Teknik Direktör','Yardımcı Antrenör','Kaleci Antrenörü','Atletik Performans Antrenörü','Altyapı Sorumlusu','Takım Sorumlusu','Doktor','Fizyoterapist','Malzemeci','Medya Sorumlusu'];
?>
<div class="split-layout">
<form method="post" enctype="multipart/form-data" class="panel form-panel live-form"><input type="hidden" name="csrf" value="<?= e(csrf()) ?>"><input type="hidden" name="action" value="staff_save"><input type="hidden" name="id" value="<?= e($edit['id']??'') ?>"><input type="hidden" name="old_photo" value="<?= e($edit['photo']??'') ?>"><div class="panel-head"><div><small>YÖNETİM & TEKNİK EKİP</small><h2><?= $edit?'Görevliyi düzenle':'Yeni görevli ekle' ?></h2></div><?php if($edit):?><a href="?section=staff">Yeni kayıt +</a><?php endif; ?></div><div class="form-grid"><label>Ad soyad<input name="name" value="<?= e($edit['name']??'') ?>" data-live="staff-name" required></label><label>Görev<select name="role" data-live="staff-role"><?php foreach($roles as $role):?><option <?= ($edit['role']??'')===$role?'selected':'' ?>><?= e($role) ?></option><?php endforeach; ?></select></label><label>Takım<select name="team_id" data-live="staff-team"><option value="">Kulüp Geneli</option><?php foreach($teams as $team):?><option value="<?= $team['id'] ?>" <?= ($edit['team_id']??0)==$team['id']?'selected':'' ?>><?= e($team['name']) ?></option><?php endforeach; ?></select></label><label>Sıralama<input type="number" name="sort_order" value="<?= e($edit['sort_order']??0) ?>"></label><label>Göreve başlangıç<input type="date" name="start_date" value="<?= e($edit['start_date']??'') ?>"></label><label>Görev bitişi<input type="date" name="end_date" value="<?= e($edit['end_date']??'') ?>"></label><label>Fotoğraf<input type="file" name="photo_file" accept="image/jpeg,image/png,image/webp" data-image-preview="staff-photo"></label><label>Fotoğraf URL<input name="photo_url" data-url-preview="staff-photo" placeholder="https://..."></label><label class="full">Biyografi / görev açıklaması<textarea name="bio" data-live="staff-bio"><?= e($edit['bio']??'') ?></textarea></label><label class="check"><input type="checkbox" name="active" <?= ($edit['active']??1)?'checked':'' ?>><span>Sitede göster</span></label></div><div class="upload-note"><b>Personel fotoğraf önerisi</b><span>Dikey 800×1000 px JPG/WEBP. Fotoğraf yoksa profesyonel silüet kullanılır.</span></div><button class="primary-button">Görevliyi Kaydet</button></form>
<aside class="preview-column sticky-preview"><div class="preview-label">CANLI PERSONEL KARTI</div><article class="staff-admin-preview"><img id="staff-photo" src="<?= e(!empty($edit['photo'])?media_url($edit['photo']):silhouette()) ?>" alt=""><small data-preview="staff-role"><?= e($edit['role']??'GÖREV') ?></small><h3 data-preview="staff-name"><?= e($edit['name']??'Ad Soyad') ?></h3><span data-preview="staff-team"><?= e($edit['team_name']??'Kulüp Geneli') ?></span><p data-preview="staff-bio"><?= e($edit['bio']??'Görev ve biyografi açıklaması') ?></p></article></aside></div>
<section class="panel"><div class="panel-head"><div><small>KULÜP ORGANİZASYONU</small><h2>Yönetim ve teknik kadro</h2></div><span><?= count($rows) ?> kişi</span></div><div class="staff-admin-grid"><?php foreach($rows as $row):?><article><img src="<?= e($row['photo']?media_url($row['photo']):silhouette()) ?>" alt=""><div><small><?= e($row['role']) ?></small><h3><?= e($row['name']) ?></h3><p><?= e($row['team_name']?:'Kulüp Geneli') ?></p></div><span class="badge <?= $row['active']?'green':'gray' ?>"><?= $row['active']?'Aktif':'Gizli' ?></span><div class="row-actions"><a href="?section=staff&edit=<?= $row['id'] ?>">Düzenle</a><form method="post" onsubmit="return confirm('Kayıt silinsin mi?')"><input type="hidden" name="csrf" value="<?= e(csrf()) ?>"><input type="hidden" name="action" value="delete_generic"><input type="hidden" name="table" value="staff"><input type="hidden" name="id" value="<?= $row['id'] ?>"><button class="danger-link">Sil</button></form></div></article><?php endforeach; ?></div></section>
