<?php
$edit = isset($_GET['edit']) ? fetch_one('SELECT * FROM teams WHERE id=?', [(int) $_GET['edit']]) : null;
$rows = fetch_all('SELECT t.*, (SELECT COUNT(*) FROM players p WHERE p.team_id=t.id AND p.active=1) player_count FROM teams t ORDER BY t.sort_order,t.id');
?>
<div class="split-layout">
<form method="post" enctype="multipart/form-data" class="panel form-panel live-form">
<input type="hidden" name="csrf" value="<?= e(csrf()) ?>"><input type="hidden" name="action" value="team_save"><input type="hidden" name="id" value="<?= e($edit['id']??'') ?>"><input type="hidden" name="old_logo" value="<?= e($edit['logo']??'') ?>"><input type="hidden" name="old_cover" value="<?= e($edit['cover_image']??'') ?>">
<div class="panel-head"><div><small>TAKIM YÖNETİMİ</small><h2><?= $edit?'Takımı düzenle':'Yeni takım oluştur' ?></h2></div><?php if($edit):?><a href="?section=teams">Yeni kayıt +</a><?php endif; ?></div>
<div class="form-grid"><label>Takım adı<input name="name" value="<?= e($edit['name']??'') ?>" data-live="team-name" required></label><label>URL kısa adı<input name="slug" value="<?= e($edit['slug']??'') ?>" placeholder="a-takim"></label><label>Kategori / yaş grubu<input name="category" value="<?= e($edit['category']??'') ?>" data-live="team-category" placeholder="Süper Amatör, U18..."></label><label>Vurgu rengi<input type="color" name="accent" value="<?= e($edit['accent']??'#e3062f') ?>" data-live-color="team-accent"></label><label class="full">Takım açıklaması<textarea name="description" data-live="team-description"><?= e($edit['description']??'') ?></textarea></label><label>Takım logosu<input type="file" name="logo_file" accept="image/jpeg,image/png,image/webp,image/gif" data-image-preview="team-logo"></label><label>Logo URL<input name="logo_url" data-url-preview="team-logo" placeholder="https://..."></label><label>Takım kapak görseli<input type="file" name="cover_file" accept="image/jpeg,image/png,image/webp" data-image-preview="team-cover"></label><label>Kapak URL<input name="cover_url" data-url-preview="team-cover" placeholder="https://..."></label><label>Sıralama<input type="number" name="sort_order" value="<?= e($edit['sort_order']??0) ?>"></label><label class="check"><input type="checkbox" name="active" <?= ($edit['active']??1)?'checked':'' ?>> <span>Takımı yayında göster</span></label></div>
<div class="upload-note"><b>Takım görsel ölçüleri</b><span>Logo: 600×600 px şeffaf PNG/WEBP. Kapak: 1600×1000 px JPG/WEBP. Her takım için farklı görsel kullanabilirsiniz.</span></div><button class="primary-button">Takımı Kaydet</button>
</form>
<aside class="preview-column sticky-preview"><div class="preview-label">CANLI TAKIM KARTI</div><div id="team-cover" class="team-admin-preview" style="--team-accent:<?= e($edit['accent']??'#e3062f') ?>;background-image:linear-gradient(180deg,rgba(16,20,28,.25),#080a0e),url('<?= e(!empty($edit['cover_image'])?media_url($edit['cover_image']):'') ?>')"><img id="team-logo" src="<?= e(!empty($edit['logo'])?media_url($edit['logo']):placeholder_logo()) ?>" alt=""><div><small data-preview="team-category"><?= e($edit['category']??'KATEGORİ') ?></small><h3 data-preview="team-name"><?= e($edit['name']??'Takım Adı') ?></h3><p data-preview="team-description"><?= e($edit['description']??'Takım açıklaması burada görünecek.') ?></p><span>Takımı incele →</span></div></div></aside>
</div>
<section class="panel"><div class="panel-head"><div><small>KAYITLI TAKIMLAR</small><h2>Yaş grupları ve kadrolar</h2></div><span><?= count($rows) ?> takım</span></div><div class="data-cards"><?php foreach($rows as $row): ?><article><img src="<?= e($row['logo']?media_url($row['logo']):placeholder_logo()) ?>" alt=""><div><small><?= e($row['category']) ?></small><h3><?= e($row['name']) ?></h3><p><?= e($row['player_count']) ?> aktif oyuncu · <?= $row['active']?'Yayında':'Gizli' ?></p></div><div class="row-actions"><a href="?section=teams&edit=<?= $row['id'] ?>">Düzenle</a><a href="<?= e(url('index.php?page=players&team='.$row['id'])) ?>" target="_blank">Görüntüle ↗</a><form method="post" onsubmit="return confirm('Takımı silmek oyuncularını da silebilir. Emin misiniz?')"><input type="hidden" name="csrf" value="<?= e(csrf()) ?>"><input type="hidden" name="action" value="delete_generic"><input type="hidden" name="table" value="teams"><input type="hidden" name="id" value="<?= $row['id'] ?>"><button class="danger-link">Sil</button></form></div></article><?php endforeach; ?></div></section>
